codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        enabled: yes
        target: 0
        threshold: null
    patch:
      default:
        enabled: yes
        target: 50
        threshold: null

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
  branches:
    - 'push'
    - 'main'
    - '4-login'