server:
  port: 9071

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  datasource:
    driver-class-name: ${DB_CLASS}
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  main:
    allow-bean-definition-overriding: 'true'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: ${R_HOST}
      port: ${R_PORT}

coolsms:
  balshin: ${PHONE}
  api: ${PHONE_API}
  secret: ${PHONE_SECRET}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}
  accessTime: ${ACCESS_TIME}
  refreshTime: ${REFRESH_TIME}

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    credentials:
      access-key: ${AWS_ACCESS}
      secret-key: ${AWS_SECRET}
    s3:
      bucket: ${AWS_BUCKET_NAME}
      url: ${AWS_URL}
    stack:
      auto: false

url: ${SERVER_URL}