server:
  port: 9071

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  datasource:
    driver-class-name: ${DB_CLASS}
    username: ${DB_USER}
    url: ${DB_URL}
    password: ${DB_PASSWORD}

  main:
    allow-bean-definition-overriding: 'true'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${R_HOST}
      port: ${R_PORT}

coolsms:
  balshin: ${PHONE}
  api: ${PHONE_API}
  secret: ${PHONE_SECRET}

jwt:
  accessSecret: ${ACCESS_SECRET}
  refreshSecret: ${REFRESH_SECRET}
  accessTime: ${ACCESS_TIME}
  refreshTime: ${REFRESH_TIME}
