version: "3"

services:

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
      - log:/var/log
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    environment:
      - TZ=Asia/Seoul
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - minsta
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  app:
    restart: always
    image: blohny/minsta:latest
    container_name: "app"
    env_file: .env
    ports:
      - "9071:9071"
    networks:
      - minsta

  redis:
    image: redis:latest
    container_name: "redis"
    env_file: .env
    ports:
      - "6379:6379"
    networks:
      - minsta

  mysql:
    image: mysql:latest
    container_name: "mysql"
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - minsta


networks:
  minsta:

volumes:
  log:
  db:
