version: "3"

services:

  redis:
    image: redis:latest
    container_name: "redis"
    env_file: .env
    ports:
      - "6379:6379"
    networks:
      - minsta

  mysql:
    image: mysql:latest
    container_name: "mysql"
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - minsta

  app:
    restart: always
    image: blohny/minsta:latest
    container_name: "app"
    env_file: .env
    ports:
      - "9071:9071"
    networks:
      - minsta

volumes:
  db:

networks:
  minsta:
