version: "3"

services:

  app:
    restart: always
    image: blohny/minsta:latest
    container_name: "app"
    env_file: .env
    volumes:
      - log:/var/log
    ports:
      - "9071:9071"

  redis:
    image: redis:latest
    container_name: "redis"
    command: --requirepass ${REDIS_PASS}
    env_file: .env
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    container_name: "mysql"
    env_file: .env
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db:
  log: